name: "deploy"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "deploy"
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            [ ! -d "k8smap-server" ]; git clone https://github.com/PaulsBecks/k8smap-server.git
            cd k8smap-server
            docker compose up --build
